class CfgPatches
{
	class 53rd_faction
	{
		author="53rd Aux Team";
		addonRootClass="53rd_aux";
		requiredAddons[]=
		{
		};
		requiredVersion=0.1;
		units[]=
		{
			"53rd_autorifleman_Hephaestus_unit",
			"53rd_gl_Hephaestus_unit",
			"53rd_marksman_Hephaestus_unit",
			"53rd_rto_Hephaestus_unit",
			"53rd_shotgun_Hephaestus_unit",
			"53rd_sl_Hephaestus_unit",
			"53rd_smg_Hephaestus_unit",
			"53rd_sniper_Hephaestus_unit",
			"53rd_recon_Hephaestus_unit",
			"53rd_autorifleman_Athena_unit",
			"53rd_gl_Athena_unit",
			"53rd_marksman_Athena_unit",
			"53rd_rto_Athena_unit",
			"53rd_shotgun_Athena_unit",
			"53rd_sl_Athena_unit",
			"53rd_smg_Athena_unit",
			"53rd_sniper_Athena_unit",
			"53rd_recon_Athena_unit",
		};
		weapons[]=
		{
		};
	};
};
class cfgWeapons
{
};
class cfgVehicles
{
	class OPTRE_UNSC_Marine_Soldier_Rifleman_AR;
	class 53rd_rifleman_Hephaestus_unit: OPTRE_UNSC_Marine_Soldier_Rifleman_AR
	{
		scope=2;
		scopeCurator=2;
		displayName="(Hephaestus) Rifleman";
		uniformClass="53rd_BDU_Slim";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"Cytech_SafetyGlasses",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"Cytech_SafetyGlasses",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_MA5C_AC",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5C_AC",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorCategory="53rd_faction";
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_rifleman_Athena_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Athena) Rifleman";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	class 53rd_autorifleman_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Autorifleman";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_M73_AC",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M73_AC",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_200Rnd_95x40_Box_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
		icon="iconManMG";
	};
	class 53rd_autorifleman_Athena_unit: 53rd_autorifleman_Hephaestus_unit
	{
		displayName="(Athena) Autorifleman";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_corpman_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Corpsman";
		linkedItems[]=
		{
			"Armor_Hephaestus_Medic",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Medic",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		icon="iconManMedic";
		backpack="OPTRE_UNSC_Rucksack_Medic_53rd";
	};
	
	class 53rd_gl_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Grenadier";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_MA5CGL",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5CGL",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_1Rnd_Smoke_Grenade_shell",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
		icon="iconManExplosive";
	};
	class 53rd_gl_Athena_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Athena) Grenadier";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Hephaestus_GL_Armor",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_Volare_airmen_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Volare) Airmen";
		linkedItems[]=
		{
			"Icarus_Cadet_Armor",
			"Icarus_Helmet_Cadet",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Icarus_Cadet_Armor",
			"Icarus_Helmet_Cadet",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_M7",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_48Rnd_5x23mm_Mag_FMJ",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
		backpack="B_Parachute";
	};
	class 53rd_Volare_SA_unit: 53rd_Volare_airmen_unit
	{
		displayName="(Volare) Flight Lead";
		linkedItems[]=
		{
			"Icarus_Pilot_Ensign",
			"Icarus_Helmet_Pilot",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Icarus_Pilot_Ensign",
			"Icarus_Helmet_Pilot",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
	};

	class 53rd_officer_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Officer";
		linkedItems[]=
		{
			"Armor_Hephaestus_Squad_Leader",
			"53rd_Beret_Hephaestus",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Squad_Leader",
			"53rd_Beret_Hephaestus",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_M6G_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_M6G_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_8Rnd_127x40_Mag_APT",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		icon="iconManLeader";
	};
	class 53rd_officer_Athena_unit: 53rd_officer_Hephaestus_unit
	{
		displayName="(Athena) Officer";
		linkedItems[]=
		{
			"53rd_M52A_Para_Y_SL",
			"53rd_Beret_Athena",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_M52A_Para_Y_SL",
			"53rd_Beret_Athena",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_marksman_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Marksman";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_Commando_Black_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_Commando_Black_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"Command_20Rnd_65_TracerR_Mag",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
		icon="iconManRecon";
	};
	class 53rd_marksman_Athena_unit: 53rd_marksman_Hephaestus_unit
	{
		displayName="(Athena) Marksman";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_rto_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) RTO";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"OPTRE_MA5C_AC",
			"OPTRE_M319s",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5C_AC",
			"OPTRE_M319s",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		backpack="MEU_11th_OPTRE_ANPRC_521_Black_AI";
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_rto_Athena_unit: 53rd_rto_Hephaestus_unit
	{
		displayName="(Athena) RTO";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_shotgun_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Shotgun";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_M45TAC_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_M45TAC_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_shotgun_Athena_unit: 53rd_shotgun_Hephaestus_unit
	{
		displayName="(Athena) Shotgun";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	class 53rd_sl_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Squad Leader";
		linkedItems[]=
		{
			"Armor_Hephaestus_Squad_leader",
			"53rd_CH252_GREY_HEV_Sealed_SL_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Squad_leader",
			"53rd_CH252_GREY_HEV_Sealed_SL_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		backpack="OPTRE_ANPRC_515";
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_sl_Athena_unit: 53rd_sl_Hephaestus_unit
	{
		displayName="(Athena) Squad Leader";
		linkedItems[]=
		{
			"53rd_M52A_Para_Y_SL",
			"53rd_CH252A_Y_BV_NCO",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_M52A_Para_Y_SL",
			"53rd_CH252A_Y_BV_NCO",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	class 53rd_smg_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) SMG";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_M7_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_M7_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_60Rnd_5x23mm_Mag_tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_smg_Athena_unit: 53rd_smg_Hephaestus_unit
	{
		displayName="(Athena) SMG";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_sniper_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Sniper";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_SRS99D_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_SRS99D_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_4Rnd_145x114_Mag_APFSDST",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		icon="iconManRecon";
		camouflage=0.40000001;
		sensitivity=4;
		threat[]={1.5,0.1,0.1};
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_sniper_Athena_unit: 53rd_sniper_Hephaestus_unit
	{
		displayName="(Athena) Sniper";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};

	class 53rd_recon_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Recon";
		linkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"Armor_Hephaestus_Rifleman",
			"53rd_CH252_GREY_HEV_Sealed_SPC_SLV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		weapons[]=
		{
			"MEU_OPTRE_M58S_AI",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MEU_OPTRE_M58S_AI",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_42Rnd_95x40_Mag_Tracer",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		icon="iconManRecon";
		camouflage=0.5;
		sensitivity=8;
		threat[]={1.2,0.1,0.1};
		backpack="OPTRE_ANPRC_515";
		editorSubcategory="53rd_Men_Hephaestus";
	};
	class 53rd_recon_Athena_unit: 53rd_recon_Hephaestus_unit
	{
		displayName="(Athena) Recon";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_rifleman_aa_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Rifleman AA";
		backpack="OPTRE_UNSC_Rucksack_M41";
		weapons[]=
		{
			"OPTRE_MA5C_AC",
			"launch_B_Titan_tna_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5C_AC",
			"launch_B_Titan_tna_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"Titan_AA",
			"Titan_AA",
			"Titan_AA",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorCategory="53rd_faction";
		editorSubcategory="53rd_Men_Hephaestus";
		icon="iconManAT";
	};
	class 53rd_rifleman_aa_Athena_unit: 53rd_rifleman_aa_Hephaestus_unit
	{
		displayName="(Athena) Rifleman AA";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
	
	class 53rd_rifleman_at_Hephaestus_unit: 53rd_rifleman_Hephaestus_unit
	{
		displayName="(Hephaestus) Rifleman AT";
		backpack="OPTRE_UNSC_Rucksack_M41";
		weapons[]=
		{
			"OPTRE_MA5C_AC",
			"OPTRE_M41_SSR",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"OPTRE_MA5C_AC",
			"OPTRE_M41_SSR",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		respawnMagazines[]=
		{
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_32Rnd_762x51_Mag_Tracer",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M41_Twin_HEAT",
			"OPTRE_M9_Frag",
			"OPTRE_M9_Frag",
			"OPTRE_M2_Smoke",
			"OPTRE_M2_Smoke_Green"
		};
		editorCategory="53rd_faction";
		editorSubcategory="53rd_Men_Hephaestus";
		icon="iconManEngineer";
	};
	class 53rd_rifleman_at_Athena_unit: 53rd_rifleman_at_Hephaestus_unit
	{
		displayName="(Athena) Rifleman AT";
		linkedItems[]=
		{
			"Armor_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		respawnLinkedItems[]=
		{
			"53rd_odst_co_Yellow_Shoulder_Rifleman",
			"53rd_CH252A_Y_BV",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"OPTRE_NVG",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		editorSubcategory="53rd_Men_Athena";
	};
};
class CfgEditorCategories
{
	class 53rd_Men;
	class 53rd_faction: 53rd_Men
	{
	displayName="[53rd] Strike Company";
	};
};
class CfgEditorSubcategories
{
	class 53rd_faction;
	class 53rd_Men_Hephaestus: 53rd_faction
	{
		displayName="[53rd] Hephaestus";
	};
	class 53rd_Men_Athena: 53rd_faction
	{
		displayName="[53rd] Athena";
	};
};
class CfgGroups
{
	class West
	{
		class 53rd_groups
		{
			name="[53rd] Unit Compositions";
			class 53rd_groups_Hephaestus_Platoon
			{
				dlc="53rd";
				name="Hephaestus";
				class 53rd_Hephaestus_squad
				{
					name="Squad (x3 teams)";
					side=1;
					faction="OPTRE_UNSC";
					rarityGroup=0.30000001;
					class Group_leader
					{
						side=1;
						vehicle="53rd_sl_Hephaestus_unit";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Group_medic
					{
						side=1;
						vehicle="53rd_corpman_Hephaestus_unit";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class ft1_leader
					{
						side=1;
						vehicle="53rd_cpl_Hephaestus_unit";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class ft1_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Hephaestus_unit";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
					class ft1_gl
					{
						side=1;
						vehicle="53rd_gl_Hephaestus_unit";
						rank="PRIVATE";
						position[]={15,-10,0};
					};
					class ft1_at
					{
						side=1;
						vehicle="53rd_rifleman_at_Hephaestus_unit";
						rank="PRIVATE";
						position[]={20,-10,0};
					};
					class ft2_leader
					{
						side=1;
						vehicle="53rd_cpl_Hephaestus_unit";
						rank="CORPORAL";
						position[]={25,-5,0};
					};
					class ft2_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Hephaestus_unit";
						rank="PRIVATE";
						position[]={30,-10,0};
					};
					class ft2_mk
					{
						side=1;
						vehicle="53rd_gl_Hephaestus_unit";
						rank="PRIVATE";
						position[]={35,-10,0};
					};
					class ft2_at
					{
						side=1;
						vehicle="53rd_marksman_Hephaestus_unit";
						rank="PRIVATE";
						position[]={40,-10,0};
					};
					class ft3_leader
					{
						side=1;
						vehicle="53rd_cpl_Hephaestus_unit";
						rank="CORPORAL";
						position[]={45,-5,0};
					};
					class ft3_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Hephaestus_unit";
						rank="PRIVATE";
						position[]={50,-10,0};
					};
					class ft3_gl
					{
						side=1;
						vehicle="53rd_gl_Hephaestus_unit";
						rank="PRIVATE";
						position[]={55,-10,0};
					};
					class ft3_aa
					{
						side=1;
						vehicle="53rd_rifleman_aa_Hephaestus_unit";
						rank="PRIVATE";
						position[]={60,-10,0};
					};
				};
				class 53rd_Hephaestus_sent1
				{
					name="Sentry (Marksmen)";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_marksman_Hephaestus_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_smg_Hephaestus_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Hephaestus_sent2
				{
					name="Sentry (Sniper)";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_sniper_Hephaestus_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_smg_Hephaestus_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Hephaestus_squad_aa
				{
					name="x2 AA";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_aa_Hephaestus_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_aa_Hephaestus_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Hephaestus_squad_at
				{
					name="x2 AT";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_at_Hephaestus_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_at_Hephaestus_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Hephaestus_aa_at
				{
					name="x2 AA/x2 AT";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_aa_Hephaestus_unit";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_at_Hephaestus_unit";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="53rd_rifleman_aa_Hephaestus_unit";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="53rd_rifleman_at_Hephaestus_unit";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
				};
			};
			class 53rd_groups_Athena_platoon
			{
				dlc="53rd";
				name="Athena";
				class 53rd_Athena_squad
				{
					name="Squad (x3 teams)";
					side=1;
					faction="OPTRE_UNSC";
					rarityGroup=0.30000001;
					class Group_leader
					{
						side=1;
						vehicle="53rd_sl_Athena_unit";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Group_medic
					{
						side=1;
						vehicle="53rd_corpman_Athena_unit";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class ft1_leader
					{
						side=1;
						vehicle="53rd_cpl_Athena_unit";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class ft1_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Athena_unit";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
					class ft1_gl
					{
						side=1;
						vehicle="53rd_gl_Athena_unit";
						rank="PRIVATE";
						position[]={15,-10,0};
					};
					class ft1_at
					{
						side=1;
						vehicle="53rd_rifleman_at_Athena_unit";
						rank="PRIVATE";
						position[]={20,-10,0};
					};
					class ft2_leader
					{
						side=1;
						vehicle="53rd_cpl_Athena_unit";
						rank="CORPORAL";
						position[]={25,-5,0};
					};
					class ft2_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Athena_unit";
						rank="PRIVATE";
						position[]={30,-10,0};
					};
					class ft2_mk
					{
						side=1;
						vehicle="53rd_gl_Athena_unit";
						rank="PRIVATE";
						position[]={35,-10,0};
					};
					class ft2_at
					{
						side=1;
						vehicle="53rd_marksman_Athena_unit";
						rank="PRIVATE";
						position[]={40,-10,0};
					};
					class ft3_leader
					{
						side=1;
						vehicle="53rd_cpl_Athena_unit";
						rank="CORPORAL";
						position[]={45,-5,0};
					};
					class ft3_ar
					{
						side=1;
						vehicle="53rd_autorifleman_Athena_unit";
						rank="PRIVATE";
						position[]={50,-10,0};
					};
					class ft3_gl
					{
						side=1;
						vehicle="53rd_gl_Athena_unit";
						rank="PRIVATE";
						position[]={55,-10,0};
					};
					class ft3_aa
					{
						side=1;
						vehicle="53rd_rifleman_aa_Athena_unit";
						rank="PRIVATE";
						position[]={60,-10,0};
					};
				};
				class 53rd_Athena_sent1
				{
					name="Sentry (Marksmen)";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_marksman_Athena_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_smg_Athena_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Athena_sent2
				{
					name="Sentry (Sniper)";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_sniper_Athena_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_smg_Athena_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Athena_recon
				{
					name="Recon";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_recon_Athena_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_recon_Athena_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Athena_squad_aa
				{
					name="x2 AA";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_aa_Athena_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_aa_Athena_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Athena_squad_at
				{
					name="x2 AT";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_at_Athena_unit";
						rank="CORPORAL";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_at_Athena_unit";
						rank="PRIVATE";
						position[]={5,-5,0};
					};
				};
				class 53rd_Athena_aa_at
				{
					name="x2 AA/x2 AT";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_rifleman_aa_Athena_unit";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_rifleman_at_Athena_unit";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="53rd_rifleman_aa_Athena_unit";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="53rd_rifleman_at_Athena_unit";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
				};
				class 53rd_Athena_cqc
				{
					name="Breacher Team";
					side=1;
					faction="OPTRE_UNSC";
					class Unit0
					{
						side=1;
						vehicle="53rd_shotgun_Athena_unit";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Unit1
					{
						side=1;
						vehicle="53rd_shotgun_Athena_unit";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Unit2
					{
						side=1;
						vehicle="53rd_smg_Athena_unit";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Unit3
					{
						side=1;
						vehicle="53rd_autorifleman_Athena_unit";
						rank="PRIVATE";
						position[]={10,-10,0};
					};
				};
			};
		};
	};
};
};