// Generated by unRap v1.06 by Kegetys

class CfgMissions {
    class Cutscenes {
        class 53rdModIntro {
            directory = "53rd_SC_aux\Main\MenuIntro\Loading-screen-1.ogv";
        };
    };
};