// Generated by unRap v1.06 by Kegetys
class CfgPatches {
    class 53rdMod_client {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1;
        requiredAddons[] = {A3_UI_F, "a3_map_altis_scenes", "a3_map_vr_scenes", "a3_map_stratis_scenes"};
    };
};